export const INIT = "@@INIT";

export const GET_MARKET_DATA_REQUEST = 'GET_MARKET_DATA_REQUEST';
export const GET_MARKET_DATA_SUCCESS = 'GET_MARKET_DATA_SUCCESS';
export const GET_MARKET_DATA_FAIL = 'GET_MARKET_DATA_FAIL';

export const GET_MARKET_QUOTES_REQUEST = 'GET_MARKET_QUOTES_REQUEST';
export const GET_MARKET_QUOTES_SUCCESS = 'GET_MARKET_QUOTES_SUCCESS';
export const GET_MARKET_QUOTES_FAIL = 'GET_MARKET_QUOTES_FAIL';

